### ISSUE TITLE
Model questions

### ISSUE THREAD

**Issue by yunruo-zhang-will** [eth-sri/DeepT#2]
I would appreciate it if anyone can tell me how the models used in the paper are trained, because I am interested in evluating the performance on models with various embedding size and hidden layer size.
So I am planing to train some new models, and I have some questions.
Should I use the standard training or adversarial training? Is there any other detail I should know?
Please reply me, much thanks!

**Comment by bonaert** [comment]
Hi @Student2Pro, thank you for your interest! 

Some of the models used in the paper were models trained using standard training, while others were specifically trained to achieve higher robustness. For the full details, [our paper](https://files.sri.inf.ethz.ch/website/papers/pldi21-transformers.pdf) explain which models were used in each section of the results and were that model originated.

**Comment by yunruo-zhang-will** [comment]
Hi @bonaert thanks for your reply! 

I've read your paper and I think it's an excellent work. The multi-norm zonotope and noise symbol reduction are remarkable designs.  I hope I can build a new verifier based on them.

Since my questions are answered, I'm closing this issue. Thanks again!
